# authoring_examples_catalog.gd
# Built-in Examples Catalog for Antigravity SimViz (DES, ABM/Hybrid, and SimOptim).
extends RefCounted

static func list_examples() -> Array:
	var items: Array = [
		{"id": "des_tandem_cell", "category": "des", "title": "Tandem Manufacturing Cell"},
		{"id": "des_mmc_failures", "category": "des", "title": "M/M/c Station with Failures"},
		{"id": "abm_corridor_crowd", "category": "abm", "title": "Pedestrian Corridor Flow"},
		{"id": "hybrid_security_gate", "category": "abm", "title": "Hybrid Security Checkpoint"},
		{"id": "opt_p1_er_allocation", "category": "optimization", "title": "1. ER Server Allocation (Parameter)"},
		{"id": "opt_p2_vip_dispatch", "category": "optimization", "title": "2. VIP Support Dispatcher (Policy)"},
		{"id": "opt_p3_conveyor_topology", "category": "optimization", "title": "3. Sorting Hub Conveyor (Topology)"}
	]
	items.append_array(list_conveyor_lab())
	return items

const LAB_DIR := "res://examples/conveyor_lab/"

# Conveyor Physics Lab scenes are generated by scripts/run_conveyor_lab.jl together with their physics checks.
static func list_conveyor_lab() -> Array:
	var f := FileAccess.open(LAB_DIR + "manifest.json", FileAccess.READ)
	if f == null:
		return []
	var parsed: Variant = JSON.parse_string(f.get_as_text())
	return parsed if parsed is Array else []

static func _load_lab_spec(example_id: String) -> Dictionary:
	if not example_id.is_valid_identifier():
		return {}
	var f := FileAccess.open(LAB_DIR + example_id + ".scenespec.json", FileAccess.READ)
	if f == null:
		return {}
	var parsed: Variant = JSON.parse_string(f.get_as_text())
	return parsed if parsed is Dictionary else {}

static func _port(id_str: String, name_str: String, dir_str: String, kind_str: String = "flow", card_str: String = "many") -> Dictionary:
	return {
		"id": id_str,
		"name": name_str,
		"direction": dir_str,
		"kind": kind_str,
		"data_type": "entity",
		"cardinality": card_str,
		"required": false
	}

static func _elem(id_str: String, name_str: String, kind_str: String, pos: Array, dims: Array, props: Dictionary, color_hex: String = "#3498db") -> Dictionary:
	var in_ports: Array = []
	var out_ports: Array = []
	if kind_str in ["queue", "server", "conveyor", "sink", "hybrid_gate"]:
		in_ports.append(_port("flow_in", "Flow In", "input", "flow", "many"))
	if kind_str in ["source", "queue", "server", "conveyor", "crowd_spawner", "hybrid_gate"]:
		out_ports.append(_port("flow_out", "Flow Out", "output", "flow", "many"))
	return {
		"id": id_str,
		"name": name_str,
		"kind": kind_str,
		"library": "SimElements/DES",
		"library_version": "1.0.0",
		"level_id": "level_0",
		"transform": {
			"position": [float(pos[0]), float(pos[1]), float(pos[2])],
			"rotation": [0.0, 0.0, 0.0],
			"scale": [1.0, 1.0, 1.0]
		},
		"geometry": {
			"shape": "box",
			"dimensions": [float(dims[0]), float(dims[1]), float(dims[2])]
		},
		"editor": {
			"graph_position": [float(pos[0]) * 20.0, float(pos[1]) * 20.0],
			"collapsed": false,
			"color": color_hex,
			"notes": ""
		},
		"properties": props,
		"input_ports": in_ports,
		"output_ports": out_ports,
		"metric_ports": []
	}

static func _conn(id_str: String, src: String, dst: String, ord: int = 1) -> Dictionary:
	return {
		"id": id_str,
		"source_element": src,
		"source_port": "flow_out",
		"target_element": dst,
		"target_port": "flow_in",
		"link_type": "flow",
		"enabled": true,
		"ordering": ord
	}

static func _base_doc(id_str: String, name_str: String, desc_str: String, elems: Array, conns: Array, mode_str: String = "des_only", abm_on: bool = false, opt: Variant = null) -> Dictionary:
	var doc := {
		"spec_version": "1.0.0",
		"scene": {
			"id": id_str,
			"name": name_str,
			"author": "Antigravity SimViz",
			"description": desc_str
		},
		"simulation": {
			"time_unit": "seconds",
			"warmup_time": 0.0,
			"max_duration": 3600.0,
			"mode": mode_str
		},
		"abm_config": {
			"enabled": abm_on,
			"model_name": "SFM",
			"parameters": {},
			"pedestrian_profiles": []
		},
		"spatial": {
			"levels": [
				{"id": "level_0", "name": "Ground Floor", "elevation": 0.0, "default_height": 4.5, "visible": true}
			],
			"bounds": [-50.0, -50.0, 0.0, 50.0, 50.0, 10.0]
		},
		"elements": elems,
		"connections": conns,
		"subgraphs": [],
		"overlays": [],
		"validation_metadata": {"is_valid": true, "diagnostic_count": 0, "validator_version": "1.0.0", "diagnostics": []},
		"product": {"name": "Entity", "mesh_type": "box", "color": [0.25, 0.75, 0.95], "width": 0.45, "height": 0.45, "depth": 0.45}
	}
	if opt is Dictionary and not opt.is_empty():
		doc["optimization"] = opt
	return doc

static func get_example_scenespec(example_id: String) -> Dictionary:
	var eid := example_id.strip_edges().to_lower()
	if eid.begins_with("conv_lab_"):
		return _load_lab_spec(eid)
	if eid == "des_tandem_cell":
		var elems := [
			_elem("Source_Raw", "Raw Parts Infeed", "source", [-18.0, 0.0, 0.0], [2.5, 2.0, 1.2], {"interarrival_time": {"type": "exponential", "mean": 2.8}, "priority": 0}, "#f39c12"),
			_elem("Queue_CNC", "CNC Staging Buffer", "queue", [-13.0, 0.0, 0.0], [3.5, 2.0, 0.8], {"capacity": 20, "discipline": "fifo"}, "#3498db"),
			_elem("Server_CNC", "CNC Machining Center", "server", [-8.0, 0.0, 0.0], [3.0, 2.2, 1.8], {"servers": 2, "service_time": {"type": "triangular", "min": 3.0, "mode": 4.5, "max": 6.5}}, "#e67e22"),
			_elem("Conveyor_Transfer", "Inter-Bay Conveyor", "conveyor", [-2.0, 0.0, 0.0], [6.0, 1.2, 0.8], {"speed": 1.5, "length": 6.0, "capacity": 8}, "#2ecc71"),
			_elem("Queue_Assembly", "Assembly Buffer", "queue", [6.0, 0.0, 0.0], [3.5, 2.0, 0.8], {"capacity": 20, "discipline": "fifo"}, "#3498db"),
			_elem("Server_Assembly", "Robotic Assembly", "server", [11.0, 0.0, 0.0], [3.0, 2.2, 1.8], {"servers": 1, "service_time": {"type": "exponential", "mean": 2.2}}, "#e67e22"),
			_elem("Sink_Finished", "Finished Goods Dock", "sink", [16.5, 0.0, 0.0], [2.5, 2.0, 1.2], {"record_sojourn": true}, "#e74c3c")
		]
		var conns := [
			_conn("c1", "Source_Raw", "Queue_CNC"),
			_conn("c2", "Queue_CNC", "Server_CNC"),
			_conn("c3", "Server_CNC", "Conveyor_Transfer"),
			_conn("c4", "Conveyor_Transfer", "Queue_Assembly"),
			_conn("c5", "Queue_Assembly", "Server_Assembly"),
			_conn("c6", "Server_Assembly", "Sink_Finished")
		]
		return _base_doc("des_tandem_cell", "Tandem Manufacturing Cell", "Two-stage CNC machining and robotic assembly line connected by a transfer conveyor.", elems, conns)

	elif eid == "des_mmc_failures":
		var elems := [
			_elem("Source_Jobs", "Work Order Arrivals", "source", [-12.0, 0.0, 0.0], [2.5, 2.0, 1.2], {"interarrival_time": {"type": "exponential", "mean": 1.5}, "priority": 0}, "#f39c12"),
			_elem("Queue_Staging", "Main Job Buffer", "queue", [-6.0, 0.0, 0.0], [4.5, 2.2, 0.8], {"capacity": 40, "discipline": "fifo"}, "#3498db"),
			_elem("Server_Cluster", "Parallel Processing Bank (c=3)", "server", [1.0, 0.0, 0.0], [3.5, 2.8, 1.8], {"servers": 3, "service_time": {"type": "exponential", "mean": 3.8}, "failure_model": "mtbf_mttr", "mtbf": 45.0, "mttr": 8.0}, "#e67e22"),
			_elem("Sink_Completed", "Completed Orders", "sink", [8.0, 0.0, 0.0], [2.5, 2.0, 1.2], {"record_sojourn": true}, "#e74c3c")
		]
		var conns := [
			_conn("c1", "Source_Jobs", "Queue_Staging"),
			_conn("c2", "Queue_Staging", "Server_Cluster"),
			_conn("c3", "Server_Cluster", "Sink_Completed")
		]
		return _base_doc("des_mmc_failures", "M/M/c Station with Failures", "Parallel 3-server cluster subject to stochastic breakdown and repair cycles.", elems, conns)

	elif eid == "abm_corridor_crowd":
		var elems := [
			_elem("Crowd_West", "West Concourse Spawner", "crowd_spawner", [-14.0, -4.0, 0.0], [2.5, 2.5, 1.0], {"spawn_rate": 1.2, "goal_x": 14.0, "goal_y": -4.0}, "#9b59b6"),
			_elem("Source_Visitors", "Visitor Entry", "source", [-14.0, 2.0, 0.0], [2.5, 2.0, 1.2], {"interarrival_time": {"type": "exponential", "mean": 2.0}, "priority": 0}, "#f39c12"),
			_elem("Queue_Lobby", "Lobby Queue", "queue", [-7.0, 2.0, 0.0], [4.0, 2.0, 0.8], {"capacity": 25, "discipline": "fifo"}, "#3498db"),
			_elem("Server_Desk", "Reception Desk", "server", [-1.0, 2.0, 0.0], [3.0, 2.2, 1.8], {"servers": 2, "service_time": {"type": "triangular", "min": 2.0, "mode": 3.5, "max": 5.0}}, "#e67e22"),
			_elem("Conveyor_Walkway", "Moving Walkway", "conveyor", [4.5, 2.0, 0.0], [6.0, 1.4, 0.5], {"speed": 1.8, "length": 6.0, "capacity": 12}, "#2ecc71"),
			_elem("Sink_Concourse", "East Concourse Exit", "sink", [13.0, 2.0, 0.0], [2.5, 2.0, 1.2], {"record_sojourn": true}, "#e74c3c")
		]
		var conns := [
			_conn("c1", "Source_Visitors", "Queue_Lobby"),
			_conn("c2", "Queue_Lobby", "Server_Desk"),
			_conn("c3", "Server_Desk", "Conveyor_Walkway"),
			_conn("c4", "Conveyor_Walkway", "Sink_Concourse")
		]
		return _base_doc("abm_corridor_crowd", "Pedestrian Corridor Flow", "Combined pedestrian concourse flow and visitor reception checkpoint.", elems, conns, "hybrid", true)

	elif eid == "hybrid_security_gate":
		var elems := [
			_elem("Source_Pax", "Passenger Arrival", "source", [-15.0, 0.0, 0.0], [2.5, 2.0, 1.2], {"interarrival_time": {"type": "exponential", "mean": 1.6}, "priority": 0}, "#f39c12"),
			_elem("Queue_PreCheck", "Document Check Queue", "queue", [-10.0, 0.0, 0.0], [3.5, 2.0, 0.8], {"capacity": 30, "discipline": "fifo"}, "#3498db"),
			_elem("Server_DocCheck", "Boarding Pass Desk", "server", [-5.0, 0.0, 0.0], [2.8, 2.0, 1.8], {"servers": 2, "service_time": {"type": "exponential", "mean": 2.4}, "routing_rule": "shortest_queue"}, "#e67e22"),
			_elem("Queue_LaneA", "X-Ray Lane A Buffer", "queue", [1.5, -3.5, 0.0], [3.5, 1.8, 0.8], {"capacity": 15, "discipline": "fifo"}, "#3498db"),
			_elem("Server_ScannerA", "X-Ray Scanner A", "server", [6.5, -3.5, 0.0], [3.0, 1.8, 1.8], {"servers": 1, "service_time": {"type": "triangular", "min": 2.0, "mode": 3.0, "max": 5.0}}, "#e67e22"),
			_elem("Queue_LaneB", "X-Ray Lane B Buffer", "queue", [1.5, 3.5, 0.0], [3.5, 1.8, 0.8], {"capacity": 15, "discipline": "fifo"}, "#3498db"),
			_elem("Server_ScannerB", "X-Ray Scanner B", "server", [6.5, 3.5, 0.0], [3.0, 1.8, 1.8], {"servers": 1, "service_time": {"type": "triangular", "min": 2.0, "mode": 3.0, "max": 5.0}}, "#e67e22"),
			_elem("Sink_Gates", "Departure Gates", "sink", [13.0, 0.0, 0.0], [2.5, 2.2, 1.2], {"record_sojourn": true}, "#e74c3c")
		]
		var conns := [
			_conn("c1", "Source_Pax", "Queue_PreCheck"),
			_conn("c2", "Queue_PreCheck", "Server_DocCheck"),
			_conn("c3", "Server_DocCheck", "Queue_LaneA", 1),
			_conn("c4", "Server_DocCheck", "Queue_LaneB", 2),
			_conn("c5", "Queue_LaneA", "Server_ScannerA"),
			_conn("c6", "Queue_LaneB", "Server_ScannerB"),
			_conn("c7", "Server_ScannerA", "Sink_Gates"),
			_conn("c8", "Server_ScannerB", "Sink_Gates")
		]
		return _base_doc("hybrid_security_gate", "Hybrid Security Checkpoint", "Dual-lane passenger screening checkpoint with shortest-queue lane balancing.", elems, conns)

	elif eid == "opt_p1_er_allocation":
		var elems := [
			_elem("Source_Patients", "ER Walk-In & Ambulance", "source", [-18.0, 0.0, 0.0], [2.8, 2.2, 1.2], {"interarrival_time": {"type": "exponential", "mean": 1.0 / 0.85}, "priority": 0}, "#f39c12"),
			_elem("Queue_Triage", "Stage 1: Triage Queue", "queue", [-12.5, 0.0, 0.0], [3.6, 2.2, 0.8], {"capacity": 60, "discipline": "fifo"}, "#3498db"),
			_elem("Server_Triage", "Stage 1: Triage Nurses (s1)", "server", [-7.5, 0.0, 0.0], [3.0, 2.2, 1.8], {"servers": 3, "service_time": {"type": "exponential", "mean": 1.0}}, "#e67e22"),
			_elem("Queue_Exam", "Stage 2: Diagnostic Queue", "queue", [-2.0, 0.0, 0.0], [3.6, 2.2, 0.8], {"capacity": 60, "discipline": "fifo"}, "#3498db"),
			_elem("Server_Exam", "Stage 2: Diagnostic / Imaging (s2)", "server", [3.0, 0.0, 0.0], [3.0, 2.2, 1.8], {"servers": 1, "service_time": {"type": "exponential", "mean": 1.0}}, "#e67e22"),
			_elem("Queue_Treat", "Stage 3: Treatment Queue", "queue", [8.5, 0.0, 0.0], [3.6, 2.2, 0.8], {"capacity": 60, "discipline": "fifo"}, "#3498db"),
			_elem("Server_Treat", "Stage 3: ER Physicians (s3)", "server", [13.5, 0.0, 0.0], [3.0, 2.2, 1.8], {"servers": 1, "service_time": {"type": "exponential", "mean": 1.0}}, "#e67e22"),
			_elem("Sink_Discharge", "ER Discharge / Admit", "sink", [19.0, 0.0, 0.0], [2.8, 2.4, 1.2], {"record_sojourn": true}, "#e74c3c")
		]
		var conns := [
			_conn("c1", "Source_Patients", "Queue_Triage"),
			_conn("c2", "Queue_Triage", "Server_Triage"),
			_conn("c3", "Server_Triage", "Queue_Exam"),
			_conn("c4", "Queue_Exam", "Server_Exam"),
			_conn("c5", "Server_Exam", "Queue_Treat"),
			_conn("c6", "Queue_Treat", "Server_Treat"),
			_conn("c7", "Server_Treat", "Sink_Discharge")
		]
		var opt := {
			"problem_id": "opt_p1_er_allocation",
			"problem_class": "parameter",
			"title": "ER Server Allocation (3-Stage Tandem Queue)",
			"decision_variables": [
				{"id": "s1", "element_id": "Server_Triage", "property": "servers", "type": "int", "lower": 1, "upper": 3, "initial": 3, "label": "Stage 1: Triage Staff (s1)"},
				{"id": "s2", "element_id": "Server_Exam", "property": "servers", "type": "int", "lower": 1, "upper": 3, "initial": 1, "label": "Stage 2: Exam Staff (s2)"},
				{"id": "s3", "element_id": "Server_Treat", "property": "servers", "type": "int", "lower": 1, "upper": 3, "initial": 1, "label": "Stage 3: Treatment Staff (s3)"}
			],
			"constraints": [
				{"id": "staff_budget", "kind": "linear_sum", "variables": ["s1", "s2", "s3"], "relation": "<=", "rhs": 5.0, "penalty_weight": 50.0, "description": "Total ER shift headcount s1 + s2 + s3 <= 5"}
			],
			"objective": {"sense": "minimize", "metric": "er_wait_mean", "secondary_metric": "total_servers", "description": "Minimize total expected queue waiting time E[W_q] (minutes)"},
			"solver": {"algorithm": "eca", "max_evaluations": 27, "population_size": 9, "replications_per_eval": 3, "sim_horizon": 500.0, "warmup_time": 80.0, "use_crn": true, "top_k": 5}
		}
		return _base_doc("opt_p1_er_allocation", "1. ER Server Allocation", "Allocate 5 clinical staff across 3 tandem ER stages (s1 + s2 + s3 <= 5) to reduce queue wait from 48.1 min ([3,1,1]) to 26.3 min ([2,2,1]).", elems, conns, "des_only", false, opt)

	elif eid == "opt_p2_vip_dispatch":
		var elems := [
			_elem("Source_VIP", "VIP Enterprise Callers (P1)", "source", [-16.0, -3.5, 0.0], [2.8, 2.0, 1.2], {"interarrival_time": {"type": "exponential", "mean": 1.25}, "priority": 1}, "#f1c40f"),
			_elem("Source_Standard", "Standard Callers (P0)", "source", [-16.0, 3.5, 0.0], [2.8, 2.0, 1.2], {"interarrival_time": {"type": "exponential", "mean": 1.0 / 2.4}, "priority": 0}, "#f39c12"),
			_elem("Queue_Dispatch", "Central Dispatch Intake", "queue", [-8.5, 0.0, 0.0], [4.2, 2.4, 0.8], {"capacity": 80, "discipline": "priority"}, "#3498db"),
			_elem("Server_Router", "State-Dependent Triage Router", "server", [-2.5, 0.0, 0.0], [3.0, 2.2, 1.8], {"servers": 4, "service_time": {"type": "exponential", "mean": 0.02}, "routing_rule": "dynamic_policy", "vip_queue_threshold": 3.0, "pool_util_threshold": 0.85}, "#9b59b6"),
			_elem("Queue_PoolA", "Dedicated VIP Bay Queue (A)", "queue", [4.0, -3.5, 0.0], [3.8, 2.0, 0.8], {"capacity": 60, "discipline": "priority"}, "#3498db"),
			_elem("Server_PoolA", "Dedicated VIP Specialists (srv_a)", "server", [9.5, -3.5, 0.0], [3.0, 2.0, 1.8], {"servers": 2, "service_time": {"type": "exponential", "mean": 1.0}}, "#e67e22"),
			_elem("Queue_PoolB", "Shared Pool Queue (B)", "queue", [4.0, 3.5, 0.0], [3.8, 2.0, 0.8], {"capacity": 80, "discipline": "fifo"}, "#3498db"),
			_elem("Server_PoolB", "Shared Pool Engineers (srv_b)", "server", [9.5, 3.5, 0.0], [3.0, 2.0, 1.8], {"servers": 2, "service_time": {"type": "exponential", "mean": 1.0}}, "#e67e22"),
			_elem("Sink_Resolved", "Tickets Resolved", "sink", [16.0, 0.0, 0.0], [2.8, 2.2, 1.2], {"record_sojourn": true}, "#e74c3c")
		]
		var conns := [
			_conn("c1", "Source_VIP", "Queue_Dispatch", 1),
			_conn("c2", "Source_Standard", "Queue_Dispatch", 2),
			_conn("c3", "Queue_Dispatch", "Server_Router"),
			_conn("c4", "Server_Router", "Queue_PoolA", 1),
			_conn("c5", "Server_Router", "Queue_PoolB", 2),
			_conn("c6", "Queue_PoolA", "Server_PoolA"),
			_conn("c7", "Queue_PoolB", "Server_PoolB"),
			_conn("c8", "Server_PoolA", "Sink_Resolved"),
			_conn("c9", "Server_PoolB", "Sink_Resolved")
		]
		var opt := {
			"problem_id": "opt_p2_vip_dispatch",
			"problem_class": "policy",
			"title": "VIP Support Dispatcher (State-Dependent Dynamic Policy)",
			"decision_variables": [
				{"id": "route_pol", "element_id": "Server_Router", "property": "routing_rule", "type": "categorical", "categories": ["prob", "shortest_queue", "dynamic_policy"], "initial": "dynamic_policy", "label": "Router Dispatch Policy"},
				{"id": "disc_b", "element_id": "Queue_PoolB", "property": "discipline", "type": "categorical", "categories": ["fifo", "priority"], "initial": "fifo", "label": "Shared Pool B Discipline"},
				{"id": "srv_a", "element_id": "Server_PoolA", "property": "servers", "type": "int", "lower": 1, "upper": 3, "initial": 2, "label": "Dedicated VIP Staff (srv_a)"},
				{"id": "srv_b", "element_id": "Server_PoolB", "property": "servers", "type": "int", "lower": 1, "upper": 3, "initial": 2, "label": "Shared Pool Staff (srv_b)"},
				{"id": "vip_q_thresh", "element_id": "Server_Router", "property": "vip_queue_threshold", "type": "policy_param", "lower": 1.0, "upper": 4.0, "initial": 3.0, "label": "VIP Overflow Queue Threshold (θ_q)"},
				{"id": "pool_util_thresh", "element_id": "Server_Router", "property": "pool_util_threshold", "type": "policy_param", "lower": 0.5, "upper": 0.98, "initial": 0.85, "label": "Shared Pool Reserve Cap (θ_ρ)"}
			],
			"constraints": [
				{"id": "vip_sla", "kind": "metric_bound", "metric": "vip_wait_mean", "relation": "<=", "rhs": 3.0, "penalty_weight": 80.0, "description": "VIP SLA: E[W_q(VIP)] <= 3.0 minutes"},
				{"id": "pool_budget", "kind": "linear_sum", "variables": ["srv_a", "srv_b"], "relation": "<=", "rhs": 4.0, "penalty_weight": 60.0, "description": "Total support engineers srv_a + srv_b <= 4"}
			],
			"objective": {"sense": "minimize", "metric": "std_wait_mean", "secondary_metric": "vip_wait_mean", "description": "Minimize Standard customer queue wait E[W_q(Std)] subject to VIP SLA <= 3.0 min"},
			"solver": {"algorithm": "policy_search", "max_evaluations": 30, "population_size": 10, "replications_per_eval": 3, "sim_horizon": 500.0, "warmup_time": 80.0, "use_crn": true, "top_k": 5}
		}
		return _base_doc("opt_p2_vip_dispatch", "2. VIP Support Dispatcher", "Synthesize a state-dependent dynamic routing & HOL priority policy across 4 servers to satisfy VIP SLA <= 3.0m while minimizing Standard wait.", elems, conns, "des_only", false, opt)

	elif eid == "opt_p3_conveyor_topology":
		var elems := [
			_elem("Source_Inbound", "Inbound Parcel Unloader", "source", [-33.0, 0.0, 0.0], [2.8, 2.0, 1.2], {"interarrival_time": {"type": "exponential", "mean": 7.5}, "priority": 0}, "#f39c12"),
			_elem("Queue_Infeed", "Induction Staging", "queue", [-28.0, 0.0, 0.0], [3.2, 2.0, 0.8], {"capacity": 25, "discipline": "fifo"}, "#3498db"),
			_elem("Conveyor_West", "Station 1 Conveyor (West)", "conveyor", [-22.5, 0.0, 0.0], [6.0, 1.2, 0.8], {"speed": 1.0, "length": 25.0, "spur_length": 10.0, "spur_mode": "spurs_10m", "layout_mode": "collinear_1d", "z_constraint": "constant_z", "capacity": 10, "routing_rule": "shortest_queue"}, "#2ecc71"),
			_elem("Conveyor_North", "Station 2 Conveyor (North)", "conveyor", [-7.5, 0.0, 0.0], [6.0, 1.2, 0.8], {"speed": 1.0, "length": 25.0, "spur_length": 10.0, "spur_mode": "spurs_10m", "layout_mode": "collinear_1d", "z_constraint": "constant_z", "capacity": 10, "routing_rule": "shortest_queue"}, "#2ecc71"),
			_elem("Conveyor_East", "Station 3 Conveyor (East)", "conveyor", [7.5, 0.0, 0.0], [6.0, 1.2, 0.8], {"speed": 1.0, "length": 25.0, "spur_length": 10.0, "spur_mode": "spurs_10m", "layout_mode": "collinear_1d", "z_constraint": "constant_z", "capacity": 10, "routing_rule": "shortest_queue"}, "#2ecc71"),
			_elem("Conveyor_South", "Station 4 Conveyor (South)", "conveyor", [22.5, 0.0, 0.0], [6.0, 1.2, 0.8], {"speed": 1.0, "length": 25.0, "spur_length": 10.0, "spur_mode": "spurs_10m", "layout_mode": "collinear_1d", "z_constraint": "constant_z", "capacity": 10, "routing_rule": "shortest_queue"}, "#2ecc71"),
			_elem("Queue_ChuteA", "Station 1 Buffer (K=2)", "queue", [-22.5, 5.0, 0.0], [2.8, 1.8, 0.8], {"capacity": 2, "discipline": "fifo"}, "#3498db"),
			_elem("Server_SorterA", "Optical Sorter 1", "server", [-22.5, 9.5, 0.0], [2.8, 1.8, 1.8], {"servers": 1, "service_time": {"type": "exponential", "mean": 20.0}}, "#e67e22"),
			_elem("Queue_ChuteB", "Station 2 Buffer (K=2)", "queue", [-7.5, 5.0, 0.0], [2.8, 1.8, 0.8], {"capacity": 2, "discipline": "fifo"}, "#3498db"),
			_elem("Server_SorterB", "Optical Sorter 2", "server", [-7.5, 9.5, 0.0], [2.8, 1.8, 1.8], {"servers": 1, "service_time": {"type": "exponential", "mean": 20.0}}, "#e67e22"),
			_elem("Queue_ChuteC", "Station 3 Buffer (K=2)", "queue", [7.5, 5.0, 0.0], [2.8, 1.8, 0.8], {"capacity": 2, "discipline": "fifo"}, "#3498db"),
			_elem("Server_SorterC", "Optical Sorter 3", "server", [7.5, 9.5, 0.0], [2.8, 1.8, 1.8], {"servers": 1, "service_time": {"type": "exponential", "mean": 20.0}}, "#e67e22"),
			_elem("Queue_ChuteD", "Station 4 Buffer (K=2)", "queue", [22.5, 5.0, 0.0], [2.8, 1.8, 0.8], {"capacity": 2, "discipline": "fifo"}, "#3498db"),
			_elem("Server_SorterD", "Optical Sorter 4", "server", [22.5, 9.5, 0.0], [2.8, 1.8, 1.8], {"servers": 1, "service_time": {"type": "exponential", "mean": 20.0}}, "#e67e22"),
			_elem("Sink_Outbound", "Outbound Shipping Docks", "sink", [0.0, 15.0, 0.0], [3.2, 2.4, 1.2], {"record_sojourn": true}, "#e74c3c")
		]
		var conns := [
			_conn("c1", "Source_Inbound", "Queue_Infeed"),
			_conn("c2", "Queue_Infeed", "Conveyor_West"),
			_conn("c3", "Conveyor_West", "Conveyor_North", 1),
			_conn("c4", "Conveyor_North", "Conveyor_East", 1),
			_conn("c5", "Conveyor_East", "Conveyor_South", 1),
			_conn("c6", "Conveyor_West", "Queue_ChuteA", 2),
			_conn("c7", "Conveyor_North", "Queue_ChuteB", 2),
			_conn("c8", "Conveyor_East", "Queue_ChuteC", 2),
			_conn("c9", "Conveyor_South", "Queue_ChuteD", 1),
			_conn("c10", "Queue_ChuteA", "Server_SorterA"),
			_conn("c11", "Queue_ChuteB", "Server_SorterB"),
			_conn("c12", "Queue_ChuteC", "Server_SorterC"),
			_conn("c13", "Queue_ChuteD", "Server_SorterD"),
			_conn("c14", "Server_SorterA", "Sink_Outbound"),
			_conn("c15", "Server_SorterB", "Sink_Outbound"),
			_conn("c16", "Server_SorterC", "Sink_Outbound"),
			_conn("c17", "Server_SorterD", "Sink_Outbound")
		]
		var opt := {
			"problem_id": "opt_p3_conveyor_topology",
			"problem_class": "topology",
			"title": "Sorting Hub Conveyor (Template-Free Bilevel Graph & 3D/2D Spatial Search)",
			"decision_variables": [
				{"id": "edge_w", "element_id": "Conveyor_West", "property": "out_edge", "type": "grammar_edge", "candidates": ["none", "Conveyor_North", "Conveyor_East", "Conveyor_South"], "initial": "Conveyor_North", "label": "Station 1 Outgoing Belt"},
				{"id": "edge_n", "element_id": "Conveyor_North", "property": "out_edge", "type": "grammar_edge", "candidates": ["none", "Conveyor_West", "Conveyor_East", "Conveyor_South"], "initial": "Conveyor_East", "label": "Station 2 Outgoing Belt"},
				{"id": "edge_e", "element_id": "Conveyor_East", "property": "out_edge", "type": "grammar_edge", "candidates": ["none", "Conveyor_West", "Conveyor_North", "Conveyor_South"], "initial": "Conveyor_South", "label": "Station 3 Outgoing Belt"},
				{"id": "edge_s", "element_id": "Conveyor_South", "property": "out_edge", "type": "grammar_edge", "candidates": ["none", "Conveyor_West", "Conveyor_North", "Conveyor_East"], "initial": "none", "label": "Station 4 Outgoing Belt (Loop Closure)"},
				{"id": "spur_mode", "element_id": "Conveyor_West", "property": "spur_mode", "type": "categorical", "categories": ["spurs_10m", "direct_ring"], "initial": "spurs_10m", "label": "Station Induction Spur Mode"},
				{"id": "layout_mode", "element_id": "Conveyor_West", "property": "layout_mode", "type": "categorical", "categories": ["collinear_1d", "folded_2d"], "initial": "collinear_1d", "label": "Spatial Coordinate Folding"},
				{"id": "route_rule", "element_id": "Conveyor_West", "property": "routing_rule", "type": "categorical", "categories": ["shortest_queue", "prob", "round_robin"], "initial": "shortest_queue", "label": "Diverter Routing Policy"}
			],
			"constraints": [
				{"id": "max_conveyor_budget", "kind": "topology_budget", "metric": "total_conveyor_length", "relation": "<=", "rhs": 65.0, "penalty_weight": 40.0, "description": "Total 3D Euclidean belt length L_total <= 65.0m"},
				{"id": "station_separation", "kind": "metric_bound", "metric": "min_station_separation", "relation": ">=", "rhs": 15.0, "penalty_weight": 100.0, "description": "Minimum pairwise 3D station distance ||p_i - p_j||_2 >= 15.0m"},
				{"id": "constant_z_elevation", "kind": "metric_bound", "metric": "z_elevation_deviation", "relation": "<=", "rhs": 0.0, "penalty_weight": 200.0, "description": "Constant floor elevation z_i == z_0 across all conveyors"},
				{"id": "port_degree_bound", "kind": "metric_bound", "metric": "max_port_degree", "relation": "<=", "rhs": 2.0, "penalty_weight": 100.0, "description": "Binary mechanical diverter/merge port limit (in-deg <= 2, out-deg <= 2)"},
				{"id": "induction_overflow_safety", "kind": "metric_bound", "metric": "deadlock_free_spurs", "relation": ">=", "rhs": 1.0, "penalty_weight": 150.0, "description": "Open acyclic topologies require 10m accumulation spurs; closed loops allow 0m direct ring"}
			],
			"objective": {"sense": "minimize", "metric": "system_sojourn_mean", "secondary_metric": "total_conveyor_length", "description": "Minimize expected parcel sojourn time E[W] = E[T_belt] + E[W_q] + E[S] (seconds)"},
			"solver": {"algorithm": "bilevel_graph_sa", "max_evaluations": 30, "population_size": 8, "replications_per_eval": 2, "sim_horizon": 300.0, "warmup_time": 40.0, "use_crn": true, "top_k": 5}
		}
		return _base_doc("opt_p3_conveyor_topology", "3. Sorting Hub Conveyor", "Discover a 60m 2D Closed-Loop recirculation ring (E[W]=48.2s) from a 100m 1D Linear Spine (E[W]=73.2s) via template-free bilevel graph mutation and 3D/2D coordinate folding.", elems, conns, "des_only", false, opt)
	return {}
